# Generated by Django 4.1.2 on 2022-10-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='code',
            new_name='model',
        ),
    ]
